### ISSUE TITLE
Lots of timeout when Nexus OSS 3.15.1 is configured with nexus3-crowd-plugin-3.6.1

### ISSUE THREAD

**Issue by gmshake** [pingunaut/nexus3-crowd-plugin#73]
nexus.log
```
2019-02-20 15:01:10,872+0800 INFO  [qtp1225702118-451]  *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - doGetAuthorizationInfo for anonymous
2019-02-20 15:01:12,409+0800 ERROR [qtp1225702118-450]  *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient - error executing query
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:313)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:279)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient.executeQuery(CachingNexusCrowdClient.java:96)
        at com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient.findRolesByUser(CachingNexusCrowdClient.java:174)
        at com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm.doGetAuthorizationInfo(CrowdAuthenticatingRealm.java:76)
        at org.apache.shiro.realm.AuthorizingRealm.getAuthorizationInfo(AuthorizingRealm.java:341)
        at org.apache.shiro.realm.AuthorizingRealm.isPermitted(AuthorizingRealm.java:462)
        at org.sonatype.nexus.security.authz.ExceptionCatchingModularRealmAuthorizer.isPermitted(ExceptionCatchingModularRealmAuthorizer.java:206)
        at org.apache.shiro.mgt.AuthorizingSecurityManager.isPermitted(AuthorizingSecurityManager.java:117)
        at org.apache.shiro.subject.support.DelegatingSubject.isPermitted(DelegatingSubject.java:162)
        at org.sonatype.nexus.security.SecurityHelper.anyPermitted(SecurityHelper.java:98)
        at org.sonatype.nexus.security.SecurityHelper.anyPermitted(SecurityHelper.java:116)
        at org.sonatype.nexus.repository.security.internal.ContentPermissionCheckerImpl.isViewPermitted(ContentPermissionCheckerImpl.java:59)
        at org.sonatype.nexus.repository.security.internal.ContentPermissionCheckerImpl.isPermitted(ContentPermissionCheckerImpl.java:134)
        at org.sonatype.nexus.repository.security.SecurityFacetSupport.ensurePermitted(SecurityFacetSupport.java:71)
        at org.sonatype.nexus.repository.security.SecurityHandler.handle(SecurityHandler.java:48)
        ...
```

It's probably regression introduced by https://github.com/pingunaut/nexus3-crowd-plugin/pull/71

PR created: https://github.com/pingunaut/nexus3-crowd-plugin/pull/74

**Comment by blop** [comment]
I have the same issue :/ 

```
2019-02-25 08:40:15,235+0000 INFO  [qtp1850963590-255] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - crowd authenticated: false
2019-02-25 08:40:19,502+0000 ERROR [qtp1850963590-77] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient - error executing query
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
`
``

**Comment by ngoossens** [comment]
@blop, PR #74 has been merged but no new release has been created yet. If you build from the master branch and install that version this issue should be resolved. I have been running a build with this fix for the last 5 days without any issues.

**Comment by blop** [comment]
Yes, I've just build it from master :)

**Comment by pingunaut** [comment]
@blop do I understand correct, that the issue still persists for you with current master :tired_face:?

**Comment by blop** [comment]
No, it's resolved with master :) thank you !

**Comment by pingunaut** [comment]
Thanks a lot to all of you!
New release is out: https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.6.2
